name: Victoriametrics Agent add-on
version: "1.130.0.2"
slug: victoria_metrics_agent
description: Victoriametrics Agent add-on for long term storage as replacement for Prometheus and InfluxDB
webui: "http://[HOST]:[PORT:8429]/"
ingress: true
ingress_port: 8429
ingress_entry: /targets
startup: services
boot: auto
host_network: true # may not be needed
ports:
  8429/tcp: 8429
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  source: ""
  remoteWriteURL: "https://xxx.yy/api/v1/write"
  additionalArguments: ""
  enableTCP6: true
  enableHTTPAuth: false
  remoteWriteHTTPAuth: false
  username: ""
  password: ""
  enableNodeExporterScrape: false
  enablePrometheusScrape: false
  prometheusScrapeHTTPS: false
  prometheusScrapeInterval: "60s"
  prometheusScrapeTimeout: "25s"
  longelivedToken: ""
  homeassistantUrl: "localhost:8123"
  dropMetricsRegex: "'entity_available|last_updated_time_seconds|state_change_created|state_change_total'"
schema:
  source: "str?"
  remoteWriteURL: "str?"
  additionalArguments: "str?"
  enableTCP6: bool
  enableHTTPAuth: bool
  remoteWriteHTTPAuth: bool
  username: "str?"
  password: "password?"
  enableNodeExporterScrape: bool
  enablePrometheusScrape: bool
  prometheusScrapeHTTPS: bool
  prometheusScrapeInterval: "str?"
  prometheusScrapeTimeout: "str?"
  longelivedToken: "password?"
  homeassistantUrl: "str?"
  dropMetricsRegex: "str?"

